# Text Classification Notebook

This notebook works on text classification using raw text and labels.
It begins by loading the dataset and reviewing the text samples.
The workflow then covers cleaning, tokenization, and feature creation.
Later cells support training, testing, and evaluating classification models.

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import string
import nltk

In [6]:
data = {

  "text": [

    "I love working with data and statistics",

    "Data visualization helps understand trends",

    "Data analysis improves business decisions",

    "Machine learning models can predict outcomes",

    "Training models requires a lot of data",

    "Supervised learning uses labeled data",

    "AI is transforming industries rapidly",

    "Artificial intelligence powers smart assistants",

    "AI systems can automate complex tasks",

    "Machine learning improves recommendation systems",

    "Data science combines statistics and programming",

    "Artificial intelligence enables self driving cars"

  ],

   

  "label": [

    "data_science",

    "data_science",

    "data_science",

    "machine_learning",

    "machine_learning",

    "machine_learning",

    "artificial_intelligence",

    "artificial_intelligence",

    "artificial_intelligence",

    "machine_learning",

    "data_science",

    "artificial_intelligence"

  ]

}

df = pd.DataFrame(data)
df

                                                 text                    label
0             I love working with data and statistics             data_science
1          Data visualization helps understand trends             data_science
2           Data analysis improves business decisions             data_science
3        Machine learning models can predict outcomes         machine_learning
4              Training models requires a lot of data         machine_learning
5               Supervised learning uses labeled data         machine_learning
6               AI is transforming industries rapidly  artificial_intelligence
7     Artificial intelligence powers smart assistants  artificial_intelligence
8               AI systems can automate complex tasks  artificial_intelligence
9    Machine learning improves recommendation systems         machine_learning
10   Data science combines statistics and programming             data_science
11  Artificial intelligence enables self driving cars  artificial_intelligence

In [7]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [8]:
df["clean_text"] = df["text"].str.lower()
df

,text,label,clean_text
0,I love working with data and statistics,data_science,i love working with data and statistics
1,Data visualization helps understand trends,data_science,data visualization helps understand trends
2,Data analysis improves business decisions,data_science,data analysis improves business decisions
3,Machine learning models can predict outcomes,machine_learning,machine learning models can predict outcomes
4,Training models requires a lot of data,machine_learning,training models requires a lot of data
5,Supervised learning uses labeled data,machine_learning,supervised learning uses labeled data
6,AI is transforming industries rapidly,artificial_intelligence,ai is transforming industries rapidly
7,Artificial intelligence powers smart assistants,artificial_intelligence,artificial intelligence powers smart assistants
8,AI systems can automate complex tasks,artificial_intelligence,ai systems can automate complex tasks
9,Machine learning improves recommendation systems,machine_learning,machine learning improves recommendation systems
10,Data science combines statistics and programming,data_science,data science combines statistics and programming
11,Artificial intelligence enables self driving cars,artificial_intelligence,artificial intelligence enables self driving cars

In [9]:
df["clean_text"]=df["clean_text"].str.replace(f" [{string.punctuation}]", "", regex=True)
df.head()

,text,label,clean_text
0,I love working with data and statistics,data_science,i love working with data and statistics
1,Data visualization helps understand trends,data_science,data visualization helps understand trends
2,Data analysis improves business decisions,data_science,data analysis improves business decisions
3,Machine learning models can predict outcomes,machine_learning,machine learning models can predict outcomes
4,Training models requires a lot of data,machine_learning,training models requires a lot of data

In [10]:
df["tokens"]=df["clean_text"].apply(word_tokenize)
df

,text,label,clean_text,tokens
0,I love working with data and statistics,data_science,i love working with data and statistics,"[i, love, working, with, data, and, statistics]"
1,Data visualization helps understand trends,data_science,data visualization helps understand trends,"[data, visualization, helps, understand, trends]"
2,Data analysis improves business decisions,data_science,data analysis improves business decisions,"[data, analysis, improves, business, decisions]"
3,Machine learning models can predict outcomes,machine_learning,machine learning models can predict outcomes,"[machine, learning, models, can, predict, outc..."
4,Training models requires a lot of data,machine_learning,training models requires a lot of data,"[training, models, requires, a, lot, of, data]"
5,Supervised learning uses labeled data,machine_learning,supervised learning uses labeled data,"[supervised, learning, uses, labeled, data]"
6,AI is transforming industries rapidly,artificial_intelligence,ai is transforming industries rapidly,"[ai, is, transforming, industries, rapidly]"
7,Artificial intelligence powers smart assistants,artificial_intelligence,artificial intelligence powers smart assistants,"[artificial, intelligence, powers, smart, assi..."
8,AI systems can automate complex tasks,artificial_intelligence,ai systems can automate complex tasks,"[ai, systems, can, automate, complex, tasks]"
9,Machine learning improves recommendation systems,machine_learning,machine learning improves recommendation systems,"[machine, learning, improves, recommendation, ..."
10,Data science combines statistics and programming,data_science,data science combines statistics and programming,"[data, science, combines, statistics, and, pro..."
11,Artificial intelligence enables self driving cars,artificial_intelligence,artificial intelligence enables self driving cars,"[artificial, intelligence, enables, self, driv..."

In [11]:
stop_words = set(stopwords.words("english"))
df["tokens"] = df["tokens"].apply(lambda x: [word for word in x if word not in stop_words])
df

,text,label,clean_text,tokens
0,I love working with data and statistics,data_science,i love working with data and statistics,"[love, working, data, statistics]"
1,Data visualization helps understand trends,data_science,data visualization helps understand trends,"[data, visualization, helps, understand, trends]"
2,Data analysis improves business decisions,data_science,data analysis improves business decisions,"[data, analysis, improves, business, decisions]"
3,Machine learning models can predict outcomes,machine_learning,machine learning models can predict outcomes,"[machine, learning, models, predict, outcomes]"
4,Training models requires a lot of data,machine_learning,training models requires a lot of data,"[training, models, requires, lot, data]"
5,Supervised learning uses labeled data,machine_learning,supervised learning uses labeled data,"[supervised, learning, uses, labeled, data]"
6,AI is transforming industries rapidly,artificial_intelligence,ai is transforming industries rapidly,"[ai, transforming, industries, rapidly]"
7,Artificial intelligence powers smart assistants,artificial_intelligence,artificial intelligence powers smart assistants,"[artificial, intelligence, powers, smart, assi..."
8,AI systems can automate complex tasks,artificial_intelligence,ai systems can automate complex tasks,"[ai, systems, automate, complex, tasks]"
9,Machine learning improves recommendation systems,machine_learning,machine learning improves recommendation systems,"[machine, learning, improves, recommendation, ..."
10,Data science combines statistics and programming,data_science,data science combines statistics and programming,"[data, science, combines, statistics, programm..."
11,Artificial intelligence enables self driving cars,artificial_intelligence,artificial intelligence enables self driving cars,"[artificial, intelligence, enables, self, driv..."

In [12]:
lemmatizer = WordNetLemmatizer()
df["lemma"]=df["tokens"].apply(lambda words:[lemmatizer.lemmatize(w) for w in words])
df

,text,label,clean_text,tokens,lemma
0,I love working with data and statistics,data_science,i love working with data and statistics,"[love, working, data, statistics]","[love, working, data, statistic]"
1,Data visualization helps understand trends,data_science,data visualization helps understand trends,"[data, visualization, helps, understand, trends]","[data, visualization, help, understand, trend]"
2,Data analysis improves business decisions,data_science,data analysis improves business decisions,"[data, analysis, improves, business, decisions]","[data, analysis, improves, business, decision]"
3,Machine learning models can predict outcomes,machine_learning,machine learning models can predict outcomes,"[machine, learning, models, predict, outcomes]","[machine, learning, model, predict, outcome]"
4,Training models requires a lot of data,machine_learning,training models requires a lot of data,"[training, models, requires, lot, data]","[training, model, requires, lot, data]"
5,Supervised learning uses labeled data,machine_learning,supervised learning uses labeled data,"[supervised, learning, uses, labeled, data]","[supervised, learning, us, labeled, data]"
6,AI is transforming industries rapidly,artificial_intelligence,ai is transforming industries rapidly,"[ai, transforming, industries, rapidly]","[ai, transforming, industry, rapidly]"
7,Artificial intelligence powers smart assistants,artificial_intelligence,artificial intelligence powers smart assistants,"[artificial, intelligence, powers, smart, assi...","[artificial, intelligence, power, smart, assis..."
8,AI systems can automate complex tasks,artificial_intelligence,ai systems can automate complex tasks,"[ai, systems, automate, complex, tasks]","[ai, system, automate, complex, task]"
9,Machine learning improves recommendation systems,machine_learning,machine learning improves recommendation systems,"[machine, learning, improves, recommendation, ...","[machine, learning, improves, recommendation, ..."
10,Data science combines statistics and programming,data_science,data science combines statistics and programming,"[data, science, combines, statistics, programm...","[data, science, combine, statistic, programming]"
11,Artificial intelligence enables self driving cars,artificial_intelligence,artificial intelligence enables self driving cars,"[artificial, intelligence, enables, self, driv...","[artificial, intelligence, enables, self, driv..."

In [14]:
df["preprocessed_text"] = df["lemma"].apply(lambda x: " ".join(x))
df

,text,label,clean_text,tokens,lemma,preprocessed_text
0,I love working with data and statistics,data_science,i love working with data and statistics,"[love, working, data, statistics]","[love, working, data, statistic]",love working data statistic
1,Data visualization helps understand trends,data_science,data visualization helps understand trends,"[data, visualization, helps, understand, trends]","[data, visualization, help, understand, trend]",data visualization help understand trend
2,Data analysis improves business decisions,data_science,data analysis improves business decisions,"[data, analysis, improves, business, decisions]","[data, analysis, improves, business, decision]",data analysis improves business decision
3,Machine learning models can predict outcomes,machine_learning,machine learning models can predict outcomes,"[machine, learning, models, predict, outcomes]","[machine, learning, model, predict, outcome]",machine learning model predict outcome
4,Training models requires a lot of data,machine_learning,training models requires a lot of data,"[training, models, requires, lot, data]","[training, model, requires, lot, data]",training model requires lot data
5,Supervised learning uses labeled data,machine_learning,supervised learning uses labeled data,"[supervised, learning, uses, labeled, data]","[supervised, learning, us, labeled, data]",supervised learning us labeled data
6,AI is transforming industries rapidly,artificial_intelligence,ai is transforming industries rapidly,"[ai, transforming, industries, rapidly]","[ai, transforming, industry, rapidly]",ai transforming industry rapidly
7,Artificial intelligence powers smart assistants,artificial_intelligence,artificial intelligence powers smart assistants,"[artificial, intelligence, powers, smart, assi...","[artificial, intelligence, power, smart, assis...",artificial intelligence power smart assistant
8,AI systems can automate complex tasks,artificial_intelligence,ai systems can automate complex tasks,"[ai, systems, automate, complex, tasks]","[ai, system, automate, complex, task]",ai system automate complex task
9,Machine learning improves recommendation systems,machine_learning,machine learning improves recommendation systems,"[machine, learning, improves, recommendation, ...","[machine, learning, improves, recommendation, ...",machine learning improves recommendation system
10,Data science combines statistics and programming,data_science,data science combines statistics and programming,"[data, science, combines, statistics, programm...","[data, science, combine, statistic, programming]",data science combine statistic programming
11,Artificial intelligence enables self driving cars,artificial_intelligence,artificial intelligence enables self driving cars,"[artificial, intelligence, enables, self, driv...","[artificial, intelligence, enables, self, driv...",artificial intelligence enables self driving car

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
tfidf_features = vectorizer.fit_transform(df["preprocessed_text"])
tfidf_df = pd.DataFrame(tfidf_features.toarray(), columns=vectorizer.get_feature_names_out())
tfidf_df

,ai,analysis,artificial,assistant,automate,business,car,combine,complex,data,...,supervised,system,task,training,transforming,trend,understand,us,visualization,working
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.322529,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.572093
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.271312,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.481246,0.481246,0.000000,0.481246,0.000000
2,0.000000,0.496573,0.000000,0.000000,0.000000,0.496573,0.000000,0.000000,0.000000,0.279954,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.279954,...,0.000000,0.000000,0.000000,0.496573,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.285720,...,0.506801,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.506801,0.000000,0.000000
6,0.444226,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.517257,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.405972,0.472713,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,0.405972,0.000000,0.000000,0.000000,0.472713,0.000000,0.000000,0.000000,0.472713,0.000000,...,0.000000,0.405972,0.472713,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.441247,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.496573,0.000000,0.279954,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.367030,0.000000,0.000000,0.000000,0.427369,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [19]:
x=tfidf_df
y=df["label"]

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [23]:
model = LogisticRegression()
model.fit(x, y)

LogisticRegression()

In [24]:
y_pred = model.predict(x)
y_pred

array(['data_science', 'data_science', 'data_science', 'machine_learning',
       'machine_learning', 'machine_learning', 'artificial_intelligence',
       'artificial_intelligence', 'artificial_intelligence',
       'machine_learning', 'data_science', 'artificial_intelligence'],
      dtype=object)

In [25]:
accuracy = accuracy_score(y, y_pred)
accuracy

1.0

In [27]:
#New Prediction 
new_text = ["AI helps automate tasks"]

In [28]:
new_text_tfidf = vectorizer.transform(new_text)
new_text_df = pd.DataFrame(new_text_tfidf.toarray(), columns=vectorizer.get_feature_names_out())

In [30]:
prediction = model.predict(new_text_df)
print(prediction)

['artificial_intelligence']